"""
Supplementary Korean translations for entries that exist in en/Game.locres but
aren't covered by the main TR dict (because they aren't in DataTables — they're
pure FText UI strings: confirmation dialogs, hover descriptions, status alerts,
codex article bodies, etc.).

Keep entries here whenever the SourceString is multi-line or contains rich tags
that wouldn't survive a round-trip through po -> manifest -> apply.py. Anything
covered by build_ko_po.TR is fine to leave there.
"""

LOCRES_EXTRA: dict[str, str] = {

    # ---- Short labels & abbreviations ----
    "ALL": "전체",
    "ALT": "ALT",
    "BIO": "바이오",
    "INS": "INS",
    "LMB": "좌클릭",
    "MMB": "휠 클릭",
    "RMB": "우클릭",
    "RED": "빨강",
    "ORE": "광석",
    "TMP": "임시",
    "Yes": "예",
    "No": "아니오",
    " and ": " 그리고 ",
    "Thumb": "엄지",
    "Thumb-2": "엄지-2",
    "Behemoth": "베헤모스",
    "Bio Node": "바이오 노드",
    "Ore Node": "광석 노드",
    "UPGRADE:": "업그레이드:",
    "x{Amount}": "x{Amount}",
    "x{Multiple}": "x{Multiple}",
    "Cargo Door": "화물 도어",
    "Sell Ships": "함선 판매",
    "{Ore} Mine": "{Ore} 광산",
    "Vortex Node": "와류 노드",
    "DOCK: {Name}": "도크: {Name}",
    "In addition,": "또한,",
    "Quantum Rift": "양자 균열",
    "Reactor Core": "원자로 코어",
    "SEARCH ITEMS": "아이템 검색",
    "Sell Modules": "모듈 판매",
    "Servitor Bot": "서비터 봇",
    "Target Drone": "표적 드론",
    "Void Anomaly": "공허 변칙",
    "[{CanBuild}]": "[{CanBuild}]",
    "Ancient Cache": "고대 보관소",
    "Arkship Stage": "방주선 단계",
    "Meteor Storm:": "운석 폭풍:",
    "New Location:": "새 위치:",
    "Small Booster": "소형 부스터",
    "Starship Part": "함선 부품",
    "Starship part": "함선 부품",
    "Station Level": "스테이션 레벨",
    "FREIGHTER: {A}": "화물선: {A}",
    "Homing Missile": "유도 미사일",
    "Large Ship Tug": "대형 함선 예인선",
    "Micro Wormhole": "마이크로 웜홀",
    "Mk 1 Freighter": "Mk 1 화물선",
    "New objectives": "새 목표",
    "Player {Index}": "플레이어 {Index}",
    "Quantum Storm:": "양자 폭풍:",
    "Small Ship Tug": "소형 함선 예인선",
    "{Name} STATION": "{Name} 스테이션",
    "Creature Swarm:": "생물 무리:",
    "Modules damaged": "모듈 손상",
    "Modules stunned": "모듈 기절",
    "Particle Storm:": "입자 폭풍:",
    "Small Aero Wing": "소형 항공 윙",
    "System Map View": "시스템 맵 뷰",
    "{A}{NewLine}{B}": "{A}{NewLine}{B}",
    "{Count}/{Total}": "{Count}/{Total}",
    "{Zone} STATION:": "{Zone} 스테이션:",
    "Modules disabled": "모듈 비활성화",
    "No valid modules": "유효한 모듈 없음",
    "SEARCH + DESTROY": "수색 + 파괴",
    "{Name}s incoming": "{Name} 접근 중",
    "Hub Storage Slots": "허브 저장 슬롯",
    "Import Demo Saves": "데모 저장 가져오기",
    "Campaign Completed": "캠페인 완료",
    "Defence Net Turret": "방어망 포탑",
    "Firestorm detected": "화염 폭풍 감지됨",
    "Ice Comet incoming": "얼음 혜성 접근 중",
    "{Station} STATION:": "{Station} 스테이션:",
    "Defence low on ammo": "방어 탄약 부족",
    "Drone Storage Slots": "드론 저장 슬롯",
    "Modules are damaged": "모듈이 손상됨",
    "Modules are stunned": "모듈이 기절함",
    "{Terminus} TERMINUS": "{Terminus} 종착점",
    " + <Armed>[Armed]</>": " + <Armed>[무장됨]</>",
    "Exotic Matter Turret": "엑조틱 매터 포탑",
    "Ice Storm incoming: ": "얼음 폭풍 접근 중: ",
    "Max Gas/Fluid Output": "최대 가스/유체 출력",
    "Modules are disabled": "모듈이 비활성화됨",
    "Modules low on power": "모듈 전력 부족",
    "Modules under attack": "모듈이 공격받음",
    "Quantum Destabiliser": "양자 불안정 장치",
    "Drone Equipment Slots": "드론 장비 슬롯",
    "Ship reactors failing": "함선 원자로 고장 임박",
    " <Fuelled>[Fuelled]</>": " <Fuelled>[연료 충전됨]</>",
    "Cloud miner is waiting": "구름 채굴기가 대기 중",
    "Electromagnetic Storm:": "전자기 폭풍:",
    "Meteor Strike incoming": "운석 충돌 접근 중",
    "Ship reactors critical": "함선 원자로 위험",
    "Meteor Storm incoming: ": "운석 폭풍 접근 중: ",
    "Cloud miners are waiting": "구름 채굴기가 대기 중",
    "Defensive testing device": "방어 테스트 장치",
    "Modules are low on power": "모듈 전력 부족",
    "Modules are under attack": "모듈이 공격받는 중",
    "Quantum Storm incoming: ": "양자 폭풍 접근 중: ",
    "Ship waiting at Shipyard": "함선이 조선소에서 대기 중",
    "<Amount> {Name}s incoming": "<Amount> {Name} 접근 중",
    "<Bold>{Name}</> has ended": "<Bold>{Name}</> 종료됨",
    "Creature Swarm incoming: ": "생물 무리 접근 중: ",
    "Freighter waiting in dock": "화물선이 도크에서 대기 중",
    "Particle Storm incoming: ": "입자 폭풍 접근 중: ",
    "Freighters waiting in dock": "화물선이 도크에서 대기 중",
    "Generators are low on fuel": "발전기 연료 부족",
    "Module containment failing": "모듈 격리 실패 임박",
    "Power Levels: <Red>75 %</>": "전력 레벨: <Red>75 %</>",
    "Reinitialising Stargate...": "스타게이트 재초기화 중...",
    "Ship waiting at Ammo Depot": "함선이 탄약 보관소에서 대기 중",
    "Ship waiting at Fuel Depot": "함선이 연료 보관소에서 대기 중",
    "Station using stored power": "스테이션이 저장 전력 사용 중",
    "To start your station off,": "스테이션을 시작하려면,",
    "Micro-Meteor Swarm incoming": "마이크로 운석 무리 접근 중",
    "Tug cannot find clear space": "예인선이 빈 공간을 찾을 수 없음",
    "<Amount> Modules are damaged": "<Amount>개 모듈 손상",
    "<Amount> Modules are stunned": "<Amount>개 모듈 기절",
    "Factory's inputs are blocked": "공장 입력이 차단됨",
    "Generators are full of waste": "발전기가 폐기물로 가득 참",
    "Scavenger waiting at station": "회수기가 스테이션에서 대기 중",
    "Set number of items to build": "건설할 아이템 수 설정",
    "<Amount> Modules are disabled": "<Amount>개 모듈 비활성화",
    "<Speaker>{Speaker}:</> {Text}": "<Speaker>{Speaker}:</> {Text}",
    "Power Levels: <Yellow>25 %</>": "전력 레벨: <Yellow>25 %</>",
    "Power Levels: <Yellow>50 %</>": "전력 레벨: <Yellow>50 %</>",
    "Scavengers waiting at station": "회수기가 스테이션에서 대기 중",
    "Solar generator needs aligning": "태양광 발전기 정렬 필요",
    "Solar generators need aligning": "태양광 발전기 정렬 필요",
    "Stargate... <Red>Inoperable</>": "스타게이트... <Red>작동 불능</>",
    "This slot is <Bold>Disabled</>": "이 슬롯은 <Bold>비활성화됨</>",
    "One of your Ships was destroyed": "함선 중 하나가 파괴됨",
    "<Bold>{PlayerName}:</> {Message}": "<Bold>{PlayerName}:</> {Message}",
    "Electromagnetic Storm incoming: ": "전자기 폭풍 접근 중: ",
    "This is a <Bold>Popup Message</>": "이것은 <Bold>팝업 메시지</>입니다",
    "<Amount> Cloud miners are waiting": "<Amount>개 구름 채굴기 대기 중",
    "<Amount> Modules are low on power": "<Amount>개 모듈 전력 부족",
    "<Amount> Modules are under attack": "<Amount>개 모듈이 공격받는 중",
    "<Bold>{Name}</> has left the game": "<Bold>{Name}</>이(가) 게임을 떠났습니다",
    "Transports cargo between stations": "스테이션 간 화물 운송",
    "Warning: <Bold>{Name}</> detected": "경고: <Bold>{Name}</> 감지됨",
    "Warning: <Bold>{Name}</> incoming": "경고: <Bold>{Name}</> 접근 중",
    "<Amount> Generators are low on fuel": "<Amount>개 발전기 연료 부족",
    "<Bold>{Name}</> has joined the game": "<Bold>{Name}</>이(가) 게임에 참여했습니다",
    "<Amount> Modules containment failing": "<Amount>개 모듈 격리 실패 임박",
    "<Bold>Reset All</> slots to defaults": "모든 슬롯을 <Bold>기본값으로 초기화</>",
    "<Bold>Reset</> this slot to defaults": "이 슬롯을 <Bold>기본값으로 초기화</>",
    "Jumpgate Buffer... <Yellow>Online</>": "점프게이트 버퍼... <Yellow>온라인</>",
    "One of your Freighters was destroyed": "화물선 중 하나가 파괴됨",
    "This is our <Red>Current Location</>": "여기는 <Red>현재 위치</>입니다",
    "Warning: <Bold>{Name}</> has started": "경고: <Bold>{Name}</> 시작됨",
    "<Amount> Factory's inputs are blocked": "<Amount>개 공장 입력이 차단됨",
    "<Amount> Generators are full of waste": "<Amount>개 발전기가 폐기물로 가득 참",
    "Do you really want to exit to desktop?": "정말 바탕화면으로 종료하시겠습니까?",
    "Void Consumption... <Red>Commencing</>": "공허 흡수... <Red>개시</>",
    "<Amount> Ships are waiting at Shipyards": "<Amount>개 함선이 조선소에서 대기 중",
    "<Amount> Solar generators need aligning": "<Amount>개 태양광 발전기 정렬 필요",
    "<Bold>Refresh</>\r\nRefresh all item data": "<Bold>새로고침</>\r\n모든 아이템 데이터 새로고침",
    "Add x 1 item to the current build queue": "현재 건설 대기열에 아이템 1개 추가",
    "Construct the <Bold>Arkship Terminal</>": "<Bold>방주선 터미널</> 건설",
    "One of your <Bold>Ships</> was destroyed": "<Bold>함선</> 중 하나가 파괴됨",
    "Open the <Bold>Add ship to queue</> menu": "<Bold>함선 대기열 추가</> 메뉴 열기",
    "<Amount> Ships are waiting at Ammo Depots": "<Amount>개 함선이 탄약 보관소에서 대기 중",
    "<Amount> Ships are waiting at Fuel Depots": "<Amount>개 함선이 연료 보관소에서 대기 중",
    "Show the <Bold>Select Freighters</> panel": "<Bold>화물선 선택</> 패널 표시",
    "Status: Jumpgate Buffer <Red>Destroyed</>": "상태: 점프게이트 버퍼 <Red>파괴됨</>",
    "Are you sure you want to delete this game?": "이 게임을 정말 삭제하시겠습니까?",
    "Are you sure you want to exit the tutorial?": "튜토리얼을 정말 종료하시겠습니까?",
    "Do you really want to exit to the main menu?": "정말 메인 메뉴로 종료하시겠습니까?",
    "Remove x 1 item from the current build queue": "현재 건설 대기열에서 아이템 1개 제거",
    "Are you sure you want to overwrite this game?": "이 게임을 정말 덮어쓰시겠습니까?",
    "One of your <Bold>Freighters</> was destroyed": "<Bold>화물선</> 중 하나가 파괴됨",
    "New tutorial videos are available in the Codex": "코덱스에서 새 튜토리얼 영상이 사용 가능합니다",
    "Destination: <Yellow>TAU System</>... Locked...": "목적지: <Yellow>타우 시스템</>... 잠김...",
    "Destroy all locks to detach and open cargo hold": "모든 잠금을 파괴해 분리하고 화물칸을 엽니다",
    "<Bold>Sell Modules</>\r\nSell the selected modules": "<Bold>모듈 판매</>\r\n선택된 모듈 판매",
    "<Yellow>Initiating</>  Intersteller  Stargate...": "<Yellow>개시 중</>  성간  스타게이트...",
    "Requires <Bold>{ObjectiveName}</> to be unlocked": "<Bold>{ObjectiveName}</> 잠금 해제 필요",
    "This is the <Bold>Description</> of this equipment": "이 장비의 <Bold>설명</>입니다",
    "<Bold>Sort Alphabetically</>\r\nSort items from A - Z": "<Bold>가나다순 정렬</>\r\n아이템을 A부터 Z 순으로 정렬",
    "Construct a Miner on this node to extract resources": "이 노드에 채굴기를 건설해 자원 추출",
    "<Bold>Copy slot</>\r\nCopy this slot's filter settings": "<Bold>슬롯 복사</>\r\n이 슬롯의 필터 설정 복사",
    "<Bold>Filter</> which item type can occupy this slot": "이 슬롯에 들어갈 수 있는 아이템 종류 <Bold>필터</>",
    "<Bold>Repair Modules</>\r\nRepair all selected modules": "<Bold>모듈 수리</>\r\n선택된 모듈 모두 수리",
    "<Bold>Repeat</> the current build queue indefinitely": "현재 건설 대기열 <Bold>무한 반복</>",
    "<Bold>Stop</>\r\nCancel all selected module operations": "<Bold>중지</>\r\n선택된 모든 모듈 작업 취소",
    "<Red>Warning:</> Void Consumption... <Red>Imminent</>": "<Red>경고:</> 공허 흡수... <Red>임박함</>",
    "Are you sure you want to sell <Bold>{Amount}</> ships?": "<Bold>{Amount}</>개 함선을 정말 판매하시겠습니까?",
    "<Bold>Remove</> all ships from the <Bold>build queue</>": "<Bold>건설 대기열</>에서 모든 함선 <Bold>제거</>",
    "Are you sure you want to reset all of your tech points?": "모든 기술 포인트를 정말 초기화하시겠습니까?",
    "Are you sure you want to sell <Bold>{Amount}</> modules?": "<Bold>{Amount}</>개 모듈을 정말 판매하시겠습니까?",
    "<Bold>Copy</> this slot's settings to all slots in module": "이 슬롯 설정을 모듈의 모든 슬롯에 <Bold>복사</>",
    "Are you sure you want to delete this entire game session?": "이 게임 세션 전체를 정말 삭제하시겠습니까?",
    "<Bold>Enable/Disable</> whether items can occupy this slot": "이 슬롯에 아이템이 들어올 수 있는지 <Bold>활성화/비활성화</>",
    "Are you sure you want to delete blueprint <Bold>{Name}</>?": "청사진 <Bold>{Name}</>을(를) 정말 삭제하시겠습니까?",
    "Construct a Bio Extractor on this node to extract resources": "이 노드에 바이오 추출기를 건설해 자원 추출",
    "Construct a Vortex Generator on this node to generate power": "이 노드에 와류 발전기를 건설해 전력 생성",
    "<Red>Error:</> Buffer Damage Detected\r\n<Red>Shutting Down</>": "<Red>오류:</> 버퍼 손상 감지됨\r\n<Red>종료 중</>",
    "<Bold>Toggle Power</>\r\nSwitch the selected modules on and off": "<Bold>전원 토글</>\r\n선택된 모듈을 켜고 끕니다",
    "{Current}\r\n<Bold>• Station Level {Level}:</> {Objective_Name}": "{Current}\r\n<Bold>• 스테이션 레벨 {Level}:</> {Objective_Name}",
    "<Bold>Save filters</>\r\nSave all item filters in this blueprint": "<Bold>필터 저장</>\r\n이 청사진의 모든 아이템 필터 저장",
    "<Bold>Trash All</>\r\nTrash the entire contents of this container": "<Bold>전체 폐기</>\r\n이 컨테이너의 모든 내용물 폐기",
    "<Bold>Infinite</>\r\nThe freighter will not leave until it is full": "<Bold>무한</>\r\n화물선은 가득 차기 전까지 떠나지 않습니다",
    "<Bold>Item Filters</>\r\nShow/hide the <Bold>Filter items</> panel": "<Bold>아이템 필터</>\r\n<Bold>아이템 필터</> 패널 표시/숨김",
    "New <Bold>tutorial videos</> are available in the <Bold>Codex</>": "<Bold>코덱스</>에 새 <Bold>튜토리얼 영상</>이 사용 가능합니다",
    "Progress the <Bold>Arkship Terminal</> to <Bold>Stage {Stage}</>": "<Bold>방주선 터미널</>을 <Bold>{Stage}단계</>로 진행",
    "Set how long the freighter will wait after last receiving items.": "마지막으로 아이템을 받은 후 화물선이 대기할 시간을 설정합니다.",
    "Set how long the freighter will wait after last unloading items.": "마지막으로 아이템을 내린 후 화물선이 대기할 시간을 설정합니다.",
    "Choose whether wormholes in <Bold>this zone</> appear in the list": "<Bold>이 구역</>의 웜홀을 목록에 표시할지 선택",
    "<Bold>Duplicate Modules</>\r\nQuickly duplicate the selected modules": "<Bold>모듈 복제</>\r\n선택된 모듈을 빠르게 복제",
    "<Bold>Reset</> all filters and other settings to <Bold>defaults</>": "모든 필터와 다른 설정을 <Bold>기본값으로 초기화</>",
    "<Bold>Save links</>\r\nSave all module connections in this blueprint": "<Bold>연결 저장</>\r\n이 청사진의 모든 모듈 연결 저장",
    "<Bold>Paste slot</>\r\nPaste previously copied slot's filter settings": "<Bold>슬롯 붙여넣기</>\r\n이전에 복사한 슬롯의 필터 설정 붙여넣기",
    "Choose whether wormholes in <Bold>other zones</> appear in the list": "<Bold>다른 구역</>의 웜홀을 목록에 표시할지 선택",
    "Construct a Quantum Extractor on this node to extract exotic matter": "이 노드에 양자 추출기를 건설해 엑조틱 매터 추출",
    "<Bold>Sort By Value</>\r\nSort items from lowest value to highest value": "<Bold>가치순 정렬</>\r\n아이템을 가치 낮은 순에서 높은 순으로 정렬",
    "Allows power to be transmitted between stations in seperate locations": "서로 다른 위치의 스테이션 간에 전력 전송 가능",
    "<Bold>Sort Ascending</>\r\nSort items from lowest value to highest value": "<Bold>오름차순 정렬</>\r\n아이템을 가치 낮은 순에서 높은 순으로 정렬",
    "<Bold>Clear Links</>\r\nRemove all links to and from the selected modules": "<Bold>연결 제거</>\r\n선택된 모듈로의 모든 연결 제거",
    "<Bold>Sort Descending</>\r\nSort items from highest value to lowest value": "<Bold>내림차순 정렬</>\r\n아이템을 가치 높은 순에서 낮은 순으로 정렬",
    "The game name cannot be empty - please enter a game name and try again.": "게임 이름은 비어 있을 수 없습니다 - 게임 이름을 입력하고 다시 시도하세요.",
    "<Bold>Advanced Options</>\r\nShow/hide the <Bold>Advanced Options</> panel": "<Bold>고급 옵션</>\r\n<Bold>고급 옵션</> 패널 표시/숨김",
    "<Bold>Decrease item amount</>\r\nDecrease the max item amount in this slot": "<Bold>아이템 수량 감소</>\r\n이 슬롯의 최대 아이템 수량 감소",
    "<Bold>Increase item amount</>\r\nIncrease the max item amount in this slot": "<Bold>아이템 수량 증가</>\r\n이 슬롯의 최대 아이템 수량 증가",
    "<Bold>Choose item amount</>\r\nSet the max item amount allowed in this slot": "<Bold>아이템 수량 선택</>\r\n이 슬롯에 허용되는 최대 아이템 수량 설정",
    "<Bold>Filter item type</>\r\nChoose which item will be allowed in this slot": "<Bold>아이템 종류 필터</>\r\n이 슬롯에 허용되는 아이템 선택",
    "Locate and destroy the following in the <Bold>{Zone Name}{Index}</> Zone:": "<Bold>{Zone Name}{Index}</> 구역에서 다음을 찾아 파괴:",
    "Stargate Control Station <Yellow>Alpha</>##\r\n<Yellow_Large>TERRA PRIME</>": "스타게이트 제어 스테이션 <Yellow>알파</>##\r\n<Yellow_Large>테라 프라임</>",
    "<Bold>Paste Setup</>\r\nPaste a previously copied module's advanced settings": "<Bold>설정 붙여넣기</>\r\n이전에 복사한 모듈의 고급 설정 붙여넣기",
    "<Bold>Create Blueprint</>\r\nCreate a new Blueprint from the selected modules": "<Bold>청사진 생성</>\r\n선택된 모듈로 새 청사진 생성",
    "<Bold>Infinite</>\r\nThe freighter will stay at this station until it is empty": "<Bold>무한</>\r\n화물선은 비워질 때까지 이 스테이션에 머무릅니다",
    "<Bold>Include Wormholes</>\r\nInclude items coming into this zone via wormholes": "<Bold>웜홀 포함</>\r\n웜홀을 통해 이 구역으로 들어오는 아이템 포함",
    "<Bold>Save advanced settings</>\r\nSave all advanced settings in this blueprint": "<Bold>고급 설정 저장</>\r\n이 청사진의 모든 고급 설정 저장",
    "<Bold>Save production</>\r\nSave all factory-related settings in this blueprint": "<Bold>생산 설정 저장</>\r\n이 청사진의 모든 공장 관련 설정 저장",
    "<Bold>Refresh Links</>\r\nRefresh all selected module links to the shortest path": "<Bold>연결 새로고침</>\r\n선택된 모든 모듈 연결을 최단 경로로 새로고침",
    "AI-Powered helper-bot that can automatically perform tasks around your station": "스테이션 주변의 작업을 자동으로 수행할 수 있는 AI 기반 도우미 봇",
    "Set the maximum amount of resources this factory will take from source modules": "이 공장이 공급원 모듈에서 가져올 최대 자원량 설정",
    "<Bold>Immediately</>\r\nThe freighter will leave as soon as it has unloaded items": "<Bold>즉시</>\r\n화물선은 아이템을 내리자마자 떠납니다",
    "Set the maximum amount of resources this shipyard will take from source modules": "이 조선소가 공급원 모듈에서 가져올 최대 자원량 설정",
    "<Bold>Change Pipe Direction</>\r\nChanges the current direction of the pipe's flow": "<Bold>파이프 방향 변경</>\r\n파이프 흐름의 현재 방향을 변경",
    "<Bold>Vent</>\r\nVents any gases or liquids currently inside this pipe or junction": "<Bold>배출</>\r\n이 파이프나 연결부에 있는 가스나 액체 배출",
    "<Bold>Take All Items</>\r\nMove all items from the selected modules into your Drone": "<Bold>모든 아이템 가져오기</>\r\n선택된 모듈의 모든 아이템을 드론으로 이동",
    "This save game already exists - please enter a different game name and try again.": "이 저장 게임이 이미 존재합니다 - 다른 게임 이름을 입력하고 다시 시도하세요.",
    "<Bold>Set to current</>\r\nSet this slot's filter to the item currently occupying it": "<Bold>현재로 설정</>\r\n현재 슬롯에 있는 아이템으로 필터 설정",
    "<Bold>Include Shipyards</>\r\nInclude production data from shipyards in this location": "<Bold>조선소 포함</>\r\n이 위치의 조선소 생산 데이터 포함",
    "<Bold>Combat Mode</>\r\nEnters Combat Mode which lets you deploy your Drone's weapons.": "<Bold>전투 모드</>\r\n드론의 무기를 사용할 수 있는 전투 모드에 진입합니다.",
    "This session name already exists - please enter a different game name and try again.": "이 세션 이름이 이미 존재합니다 - 다른 게임 이름을 입력하고 다시 시도하세요.",
    "<Bold>Show Links</>\r\nChoose whether to show all module links when in the status view.": "<Bold>연결 표시</>\r\n상태 뷰에서 모든 모듈 연결 표시 여부 선택",
    "Failed to start this game.\r\n\r\nIf this is an online session you may need to go online.": "이 게임을 시작하지 못했습니다.\r\n\r\n온라인 세션이라면 온라인으로 전환해야 할 수 있습니다.",
    "<Bold>Align Ships</>\r\nAlign all selected ships to a grid and facing the same direction": "<Bold>함선 정렬</>\r\n선택된 모든 함선을 격자에 맞추고 같은 방향으로 정렬",
    "<Bold>Show Labels</>\r\nChoose whether to show a module's label when in the status view.": "<Bold>라벨 표시</>\r\n상태 뷰에서 모듈의 라벨 표시 여부 선택",
    "New objectives have become available in the <Bold>Objectives Panel</>:\r\n{Objectives}\r\n": "<Bold>목표 패널</>에 새 목표가 사용 가능해졌습니다:\r\n{Objectives}\r\n",
    "The maximum rate of liquids/gases that can be output by this module to connected pipes": "이 모듈이 연결된 파이프로 출력할 수 있는 최대 액체/가스 속도",
    "<Bold>Build Mode</>\r\nOpens the Build Menu which lets you construct new station modules.": "<Bold>건설 모드</>\r\n새 스테이션 모듈을 건설할 수 있는 건설 메뉴를 엽니다.",
    "<Bold>Include Factories</>\r\nInclude production data from all factories in this location": "<Bold>공장 포함</>\r\n이 위치의 모든 공장 생산 데이터 포함",
    "<Bold>20 seconds</>\r\nThe freighter will stay at this station for a maximum of 20 seconds": "<Bold>20초</>\r\n화물선은 이 스테이션에 최대 20초 동안 머무릅니다",
    "<Bold>60 seconds</>\r\nThe freighter will stay at this station for a maximum of 60 seconds": "<Bold>60초</>\r\n화물선은 이 스테이션에 최대 60초 동안 머무릅니다",
    "<Bold>Equipment Slot {Slot}</>\r\nDrop equipment here to enhance your Drone's capabilities": "<Bold>장비 슬롯 {Slot}</>\r\n여기에 장비를 드롭해 드론 능력 강화",
    "<Bold>Label</>\r\nSet a custom label that is displayed in the <Bold>station status view</>": "<Bold>라벨</>\r\n<Bold>스테이션 상태 뷰</>에 표시되는 사용자 라벨 설정",
    "<Bold>Copy Setup</>\r\nCopy this module's advanced settings so it can be pasted into another": "<Bold>설정 복사</>\r\n이 모듈의 고급 설정을 복사해 다른 곳에 붙여넣기 가능",
    "<Bold>Include Depots</>\r\nInclude production data from fuel and ammo depots in this location": "<Bold>보관소 포함</>\r\n이 위치의 연료 및 탄약 보관소 생산 데이터 포함",
    "Completing this objective will <Bold>end the BETA</>.\r\n\r\nAre you sure you want to continue?": "이 목표를 완료하면 <Bold>베타가 종료됩니다</>.\r\n\r\n계속하시겠습니까?",
    "Completing this objective will <Bold>end the demo</>.\r\n\r\nAre you sure you want to continue?": "이 목표를 완료하면 <Bold>데모가 종료됩니다</>.\r\n\r\n계속하시겠습니까?",
    "<Bold>Show Pipe Flow</>\r\nChoose whether to show all pipe's flow displays in the status view.": "<Bold>파이프 흐름 표시</>\r\n상태 뷰에서 모든 파이프의 흐름 표시 여부 선택",
    "<Bold>20 seconds</>\r\nThe freighter will leave if it has not received any items for 20 seconds": "<Bold>20초</>\r\n화물선이 20초 동안 아무 아이템도 받지 않으면 떠납니다",
    "<Bold>20 seconds</>\r\nThe freighter will leave if it has not unloaded any items for 20 seconds": "<Bold>20초</>\r\n화물선이 20초 동안 아무 아이템도 내리지 않으면 떠납니다",
    "<Bold>60 seconds</>\r\nThe freighter will leave if it has not received any items for 60 seconds": "<Bold>60초</>\r\n화물선이 60초 동안 아무 아이템도 받지 않으면 떠납니다",
    "<Bold>Select Connected</>\r\nExpand selection to all modules connected to the current selection": "<Bold>연결된 모듈 선택</>\r\n현재 선택과 연결된 모든 모듈로 선택 확장",
    "<Bold>Vent All</>\r\nVents all gases or liquids from the <Bold>entire connected pipe network</>": "<Bold>전체 배출</>\r\n<Bold>연결된 전체 파이프 네트워크</>의 모든 가스나 액체 배출",
    "Set the maximum minute's worth of resources this power generator will take from source modules": "이 발전기가 공급원 모듈에서 가져올 최대 분당 자원량 설정",
    "Set the maximum amount of items this factory will store in its output before stopping production": "이 공장이 생산을 중단하기 전 출력에 저장할 최대 아이템 수량 설정",
    "<Bold>Codex</>\r\nOpens the Codex which contains a great deal of useful information about the game.": "<Bold>코덱스</>\r\n게임에 관한 유용한 정보가 많이 담긴 코덱스를 엽니다.",
    "<Bold>Include Power Generators</>\r\nInclude production data from power generators in this location": "<Bold>발전기 포함</>\r\n이 위치의 발전기 생산 데이터 포함",
    "<Bold>Priority</>\r\nIncrease this module's priority when receiving resources (<Bold>1 = lowest</>)": "<Bold>우선순위</>\r\n자원 수신 시 이 모듈의 우선순위 (<Bold>1 = 최저</>)",
    "<Bold>Refresh Links</>\r\nOptimises all Links to take the shortest possible route to linked modules": "<Bold>연결 새로고침</>\r\n연결된 모듈로 가는 모든 연결을 최단 경로로 최적화",
    "The maximum number of items per minute this module can send through its connectors to linked modules": "이 모듈이 연결관을 통해 연결된 모듈로 보낼 수 있는 분당 최대 아이템 수",
    "<Bold>Show Possible</>\r\nShow maximum possible usage/production if maximum efficiency has been achieved": "<Bold>가능한 최대값 표시</>\r\n최대 효율 시 가능한 최대 사용량/생산량 표시",
    "Set the maximum time the freighter will wait at this station - even if it still has items to drop off.": "이 스테이션에서 화물선이 대기할 최대 시간 설정 - 내릴 아이템이 남아있어도 적용됩니다.",
    "Set the maximum time the freighter will wait at this station - even if items are still being received.": "이 스테이션에서 화물선이 대기할 최대 시간 설정 - 아이템을 계속 받고 있어도 적용됩니다.",
    "Start at <Bold>Station Level 6</> in the Gas Giant Titania with extra starting resources and equipment": "추가 시작 자원과 장비를 갖고 가스 행성 티타니아의 <Bold>스테이션 레벨 6</>에서 시작합니다",
    "<Bold>Build Upgraded Modules</>\r\nSelect to build the highest available upgrade for each module directly": "<Bold>업그레이드 모듈 건설</>\r\n각 모듈에서 사용 가능한 최고 업그레이드를 직접 건설하도록 선택",
    "<Bold>Show Tug Links</>\r\nChoose whether to show a module's tug links and destination in the status view.": "<Bold>예인선 연결 표시</>\r\n상태 뷰에서 모듈의 예인선 연결과 목적지 표시 여부 선택",
    "<Bold>Show Item Send Rates</>\r\nChoose whether to show a module's item send rates when in the status view.": "<Bold>아이템 전송 속도 표시</>\r\n상태 뷰에서 모듈의 아이템 전송 속도 표시 여부 선택",
    "<Bold>Calculator</>\r\nOpens a calculator tool which lets you enter any maths expression and see the result.": "<Bold>계산기</>\r\n수식을 입력하고 결과를 볼 수 있는 계산기 도구를 엽니다.",
    "Start within the Asteroid Belt in the Tau System: A location with adundant basic resources and few hostiles": "타우 시스템의 소행성 벨트에서 시작: 풍부한 기본 자원과 적은 적대 세력이 있는 위치",
    "Do you really want to cancel all tutorial popups?\r\n\r\nYou can access these at any time from the <Bold>CODEX</>.": "정말 모든 튜토리얼 팝업을 취소하시겠습니까?\r\n\r\n언제든 <Bold>코덱스</>에서 다시 액세스할 수 있습니다.",
    "<Bold>Multi-Select Mode</>\r\nSelect multiple modules and easily apply functions to all of them at the same time.": "<Bold>다중 선택 모드</>\r\n여러 모듈을 선택하고 동시에 모든 모듈에 기능을 쉽게 적용합니다.",
    "Choose whether the popup that appears when you hover over this type of object is minimal or expanded by default": "이런 종류의 객체에 호버할 때 표시되는 팝업이 최소화될지 확장될지 기본값 선택",
    "We found some save-games from the <Bold>Outworld Station Demo</> - would you like to <Bold>import</> these now?": "<Bold>Outworld Station 데모</>의 저장 게임을 찾았습니다 - 지금 <Bold>가져오시겠습니까</>?",
    "<Bold>Duplicate Module</>\r\nPlace an exact copy of this station module including all settings and transport links": "<Bold>모듈 복제</>\r\n모든 설정과 운송 연결을 포함해 이 스테이션 모듈의 정확한 복사본 배치",
    "<Bold>Link all</>\r\nChoose a module to link all the selected modules to\r\n\r\n<Bold>[HOLD ALT]</>: Swap link direction": "<Bold>전체 연결</>\r\n선택된 모든 모듈을 연결할 모듈 선택\r\n\r\n<Bold>[ALT 누르기]</>: 연결 방향 전환",
    "<Bold>Repair Mode</>\r\nEnters Repair Mode which lets you repair damaged and disabled station modules with your Drone.": "<Bold>수리 모드</>\r\n드론으로 손상되거나 비활성화된 스테이션 모듈을 수리하는 수리 모드에 진입합니다.",
    "Choose whether the cursor should be locked in position when you middle-click-drag with your mouse to pan the camera view": "휠 클릭 드래그로 카메라 뷰를 팬할 때 커서를 위치에 고정할지 선택",
    "<Bold>Sell Mode</>\r\nEnters Sell Mode which lets you deconstruct station modules with your Drone and recoup all materials.": "<Bold>판매 모드</>\r\n드론으로 스테이션 모듈을 해체하고 모든 재료를 회수하는 판매 모드에 진입합니다.",
    "<Bold>Recommended for new players:</> Repair The Gate and escape the doomed Terra System before it is consumed by The Void": "<Bold>새 플레이어 추천:</> 공허에 흡수되기 전에 게이트를 수리하고 멸망하는 테라 시스템에서 탈출",
    "<Bold>Status View Colour</>\r\nChoose a colour highlight for this module's status-view label and icon (<Bold>1 = lowest</>).": "<Bold>상태 뷰 색상</>\r\n이 모듈의 상태 뷰 라벨과 아이콘 색상 선택 (<Bold>1 = 최저</>).",
    "Choose whether the cursor should be locked in position when you right-click-drag with your mouse to rotate the camera view": "우클릭 드래그로 카메라 뷰를 회전할 때 커서를 위치에 고정할지 선택",
    "<Bold>Link Mode</>\r\nEnters Link Mode which lets you automate supply chains by linking source and destination modules together.": "<Bold>연결 모드</>\r\n공급원 모듈과 대상 모듈을 연결하여 공급망을 자동화하는 연결 모드에 진입합니다.",
    "Complete <Bold>Main Mission Objectives</> to progress the story and unlock new <Bold>technologies, modules, parts and ships</>.": "<Bold>주요 미션 목표</>를 완료해 스토리를 진행하고 새 <Bold>기술, 모듈, 부품, 함선</>을 잠금 해제합니다.",
    "<Bold>Add Custom To-Do Task</>\r\nLets you add a custom task to your To-Do List which is also shared with all multiplayer players.": "<Bold>사용자 작업 추가</>\r\n모든 멀티플레이어와 공유되는 할 일 목록에 사용자 작업을 추가합니다.",
    "<Bold>Include Resource Collectors</>\r\nInclude production data from mines, cloud-miners and other resource collectors in this location": "<Bold>자원 수집기 포함</>\r\n이 위치의 채굴기, 구름 채굴기, 기타 자원 수집기 생산 데이터 포함",
    "<Bold>Use Quantum Storage First</>\r\nEnable this to use items and materials from Quantum Storage before your Drone Inventory when building": "<Bold>양자 저장소 우선 사용</>\r\n건설 시 드론 인벤토리보다 양자 저장소의 아이템과 재료를 우선 사용하도록 활성화",
    "<Bold>Insulated</>\r\nThis module can store or process <Bold>radioactive</> materials safely without damaging nearby machinery or your Drone": "<Bold>차폐됨</>\r\n주변 기계나 드론에 손상을 주지 않고 <Bold>방사성</> 물질을 안전하게 저장 또는 처리할 수 있습니다",
    "<Bold>DECOMISSION</> THIS STATION\r\n<Subtext>ALL ITEMS AND MATERIALS ABOVE A CERTAIN VALUE WILL BE PACKAGED AND SENT TO YOUR MAIN STATION</>": "이 스테이션 <Bold>폐기</>\r\n<Subtext>일정 가치 이상의 모든 아이템과 재료는 포장되어 메인 스테이션으로 전송됩니다</>",
    "<Bold>Efficiency</>\r\nDisplays how efficient this Solar Panel is - solar panels become <Bold>less efficient</> the more are connected together.": "<Bold>효율</>\r\n이 태양광 패널의 효율을 표시 - 태양광 패널은 더 많이 연결될수록 <Bold>효율이 떨어집니다</>.",
    "Are you sure you want to decomission this station?\r\n\r\nAll items, parts and materials above a certain value will be packaged and sent to your main station.": "이 스테이션을 정말 폐기하시겠습니까?\r\n\r\n일정 가치 이상의 모든 아이템, 부품, 재료는 포장되어 메인 스테이션으로 전송됩니다.",
    "This <Bold>Outworld Station</> build is currently <Bold>locked</>.\r\n\r\nPlease check our <Bold>Steam Page</> for information on when you can play this build.": "이 <Bold>Outworld Station</> 빌드는 현재 <Bold>잠겨 있습니다</>.\r\n\r\n이 빌드를 플레이할 수 있는 시점에 대한 정보는 <Bold>Steam 페이지</>를 확인하세요.",
    "<Bold>Volatile</>\r\nThis module stores or processes explosive compounds and will <Bold>explode</> if hit by meteors or enemy fire, damaging nearby structures": "<Bold>휘발성</>\r\n이 모듈은 폭발성 화합물을 저장 또는 처리하며 운석이나 적의 공격을 받으면 <Bold>폭발</>해 주변 구조물을 손상시킵니다",
    "Thanks for participating in this <Bold>Outworld Station BETA</>\r\n\r\nPlease don't forget to head over to our <Bold>Discord</> to discuss and report any bugs you found.": "<Bold>Outworld Station 베타</>에 참여해 주셔서 감사합니다\r\n\r\n발견하신 버그를 토론하고 보고하려면 <Bold>Discord</>를 잊지 말고 방문해 주세요.",
    "<Bold>Production Overview</>\r\nOpens the <Bold>Production Overview Panel</> which gives you a summary of all items, parts and materials your station is using and producing.": "<Bold>생산 개요</>\r\n스테이션이 사용 및 생산 중인 모든 아이템, 부품, 재료의 요약을 보여주는 <Bold>생산 개요 패널</>을 엽니다.",
    "<Bold>Panels in Network</>\r\nDisplays how many Solar Panels are connected to this power network - solar panels become <Bold>less efficient</> the more are connected together.": "<Bold>네트워크의 패널 수</>\r\n이 전력 네트워크에 연결된 태양광 패널 수 표시 - 태양광 패널은 더 많이 연결될수록 <Bold>효율이 떨어집니다</>.",
    "<Bold>Alignment</>\r\nShows if this solar panel has been aligned to this location's <Bold>sun direction</>. \r\nAlign to the current sun direction by <Bold>dragging</> with your drone.": "<Bold>정렬</>\r\n이 태양광 패널이 이 위치의 <Bold>태양 방향</>에 정렬되었는지 표시합니다. \r\n드론으로 <Bold>드래그</>하여 현재 태양 방향에 정렬하세요.",
    "Outworld Station is currently classed as <Bold>Early Access</>.\r\n\r\nThis means that you may encounter minor or major <Bold>bugs</> and features may be <Bold>missing</> or <Bold>incomplete</>.": "Outworld Station은 현재 <Bold>얼리 액세스</>로 분류됩니다.\r\n\r\n이는 작거나 큰 <Bold>버그</>를 만날 수 있고 기능이 <Bold>누락</>되거나 <Bold>미완성</>일 수 있다는 의미입니다.",

    # ---- Long-form Codex articles & guides ----
    "If this is your first game it is <Bold>strongly</> recommended that you <Bold>play the Prologue</> which includes a tutorial on how to play.\r\n\r\nWould you like to <Bold>play the Prologue</> now instead?":
        "이 게임을 처음 시작하신다면, 게임 방법 튜토리얼이 포함된 <Bold>프롤로그를 플레이</>하시는 것을 <Bold>강력히</> 권장합니다.\r\n\r\n지금 대신 <Bold>프롤로그를 플레이</>하시겠습니까?",
    "<Bold>Containment Chamber</>\r\nThis module can store or process <Bold>antimatter</> safely as long as it is not damaged and has power. If power fails then any stored antimatter will <Bold>explode</> after a short delay.":
        "<Bold>격리 챔버</>\r\n이 모듈은 손상되지 않고 전력이 공급되는 한 <Bold>반물질</>을 안전하게 저장 또는 처리할 수 있습니다. 전력이 끊기면 저장된 반물질은 짧은 지연 후 <Bold>폭발</>합니다.",
    "Congratulations, you have completed the game's Main Campaign and will now enter <Bold>Endless Mode</>! Continue building, exploring, and expanding your station with no further story constraints. Thank you for playing!":
        "축하합니다, 게임의 메인 캠페인을 완료하셨고 이제 <Bold>엔들리스 모드</>에 진입합니다! 더 이상 스토리 제약 없이 스테이션을 계속 건설하고 탐험하고 확장하세요. 플레이해 주셔서 감사합니다!",
    "NOTE: We use Steam Matchmaking to find sessions so you will only see sessions with the same Steam Download Region set as yours.\r\nIf you are looking for a specific session, please make sure you have the same Download Region set as the one you are trying to find.":
        "참고: 세션을 찾기 위해 Steam 매치메이킹을 사용하므로, 동일한 Steam 다운로드 지역으로 설정된 세션만 표시됩니다.\r\n특정 세션을 찾고 있다면, 찾으려는 세션과 동일한 다운로드 지역으로 설정되어 있는지 확인하세요.",
    "Thanks for playing the <Bold>Outworld Station Demo</>!\r\n\r\nThere will be so much more to build and explore in the full game.\r\n\r\nPlease wishlist us on Steam to know when the full version is released.\r\n\r\nThank you!":
        "<Bold>Outworld Station 데모</>를 플레이해 주셔서 감사합니다!\r\n\r\n정식 버전에는 훨씬 더 많은 건설과 탐험이 기다리고 있습니다.\r\n\r\n정식 버전 출시 시점을 알기 위해 Steam에서 위시리스트에 추가해 주세요.\r\n\r\n감사합니다!",
    "As you explore you may come across <Bold>Alien Artifacts</> floating in space or hidden inside crashed starships or other containers.\r\n\r\nThese can be dragged back to your station and dropped into the <Bold>Equipment Station</> to extract <Bold>Tech Points</> and possibly other rewards.\r\n\r\nNew <Bold>Alien Artifacts</> may also be discovered by exploring planets and other locations using your scanning equipment.":
        "탐험 중에 우주에 떠다니거나 추락한 함선 또는 기타 컨테이너에 숨겨진 <Bold>외계 유물</>을 발견할 수 있습니다.\r\n\r\n이를 스테이션으로 끌어와 <Bold>장비 정거장</>에 드롭하여 <Bold>기술 포인트</>와 기타 보상을 추출할 수 있습니다.\r\n\r\n스캐닝 장비를 사용해 행성과 기타 위치를 탐험하여 새로운 <Bold>외계 유물</>을 발견할 수도 있습니다.",
    "<Bold>Freighters</> can be used to automate moving resources between seperate parts of your station - such as  <Bold>Miners</>.\r\n\r\nTo use a freighter, construct at least 2 <Bold>Freighter Docks</> and assign a freighter to it.\r\n\r\nNext set up a <Bold>route</> for the freighter by clicking on its dock and choosing <Bold>destinations</> from a list of all freighter docks at your station.\r\n\r\nYou can also set the freighter to <Bold>wait</> at each station for a specific time, or until certain conditions are met (e.g. full storage).":
        "<Bold>화물선</>은 <Bold>채굴기</>처럼 스테이션의 서로 다른 부분 간에 자원을 자동으로 이동하는 데 사용할 수 있습니다.\r\n\r\n화물선을 사용하려면 최소 2개의 <Bold>화물선 도크</>를 건설하고 화물선을 할당하세요.\r\n\r\n다음으로 도크를 클릭해 스테이션의 모든 화물선 도크 목록에서 <Bold>목적지</>를 선택하여 화물선의 <Bold>경로</>를 설정합니다.\r\n\r\n화물선을 각 스테이션에서 특정 시간 동안 또는 특정 조건이 충족될 때까지(예: 저장소 가득 참) <Bold>대기</>하도록 설정할 수도 있습니다.",
    "The <Bold>Arkship Terminal</> serves as a nexus for constructing the <Bold>Intergalactic Arkship</>.\r\n\r\nProgressing the Arkship Terminal through its various stages will require resources, items and unique rewards from objectives. Each stage will reveal new buildable modules and unlock new game systems.\r\n\r\nProgressing the Arkship Terminal to its final stage will complete the game's main story.":
        "<Bold>방주선 터미널</>은 <Bold>은하 간 방주선</>을 건설하기 위한 거점 역할을 합니다.\r\n\r\n방주선 터미널을 각 단계로 진행하려면 자원, 아이템, 그리고 목표에서 얻은 고유 보상이 필요합니다. 각 단계마다 건설 가능한 새 모듈과 새 게임 시스템이 잠금 해제됩니다.\r\n\r\n방주선 터미널을 최종 단계까지 진행하면 게임 메인 스토리가 완료됩니다.",
    "You may now receive objectives that require the <Bold>largest classes</> of starships to complete. \r\n\r\nThese can be constructed in the <Bold>Heavy Shipyard</> module which you have just unlocked.\r\n\r\nLargest class ships generally use a more <Bold>complete</> set of parts than smaller ships and may require additional research to complete.":
        "이제 가장 <Bold>큰 등급</>의 함선이 필요한 목표를 받을 수 있습니다.\r\n\r\n방금 잠금 해제한 <Bold>중형 조선소</> 모듈에서 이 함선들을 건조할 수 있습니다.\r\n\r\n가장 큰 등급의 함선은 일반적으로 작은 함선보다 더 <Bold>완전한</> 부품 세트를 사용하며 완성하려면 추가 연구가 필요할 수 있습니다.",
    "Ships are constructed in the <Bold>Shipyard</>.\r\n\r\nClick the <Bold>+</> button to open the <Bold>ship build menu</> and choose a ship to construct. The shipyard will then automatically pull required <Bold>parts and materials</> from your station and start construction.\r\n\r\nOnce a ship is complete it will be <Bold>launched</> from the shipyard. You can then send it to objectives, exoplanet missions, or other shipyards.":
        "함선은 <Bold>조선소</>에서 건조됩니다.\r\n\r\n<Bold>+</> 버튼을 클릭해 <Bold>함선 건조 메뉴</>를 열고 건조할 함선을 선택합니다. 조선소는 자동으로 필요한 <Bold>부품과 재료</>를 스테이션에서 가져와 건조를 시작합니다.\r\n\r\n함선이 완성되면 조선소에서 <Bold>발진</>됩니다. 그 후 목표, 외계행성 임무, 다른 조선소로 보낼 수 있습니다.",
    "The <Bold>Production Overview Panel</> is a useful tool for optimising your stations. Open the panel by clicking the <Bold>Production Overview</> button at the top of the screen.\r\n\r\nThe panel shows all the items, parts and materials being produced and used by your station, as well as how many of each you have in storage. You can <Bold>filter</> the panel to only show certain locations, modules or items.":
        "<Bold>생산 개요 패널</>은 스테이션을 최적화하는 데 유용한 도구입니다. 화면 상단의 <Bold>생산 개요</> 버튼을 클릭하여 패널을 엽니다.\r\n\r\n패널은 스테이션이 생산 및 사용 중인 모든 아이템, 부품, 재료와 각각 저장소에 얼마나 있는지를 보여줍니다. 패널을 <Bold>필터</>하여 특정 위치, 모듈 또는 아이템만 표시할 수 있습니다.",
    "The <Bold>Space Elevator</> is a massive construction that can lift valuable, high-level items, materials and resources from the surface of <Bold>habitable planets</> up to your station.\r\n\r\nUnlike <Bold>Exoplanet Operations</>, the Space Elevator allows your station to receive a <Bold>continuous</> stream of resources from the planet's surface as long as it is in operation.":
        "<Bold>우주 엘리베이터</>는 <Bold>거주 가능한 행성</> 표면에서 귀중하고 고급의 아이템, 재료, 자원을 스테이션으로 들어 올릴 수 있는 거대한 건축물입니다.\r\n\r\n<Bold>외계행성 운영</>과 달리, 우주 엘리베이터는 작동 중인 한 행성 표면에서 스테이션으로 자원의 <Bold>지속적인</> 흐름을 받을 수 있게 합니다.",
    "Use the <Bold>Equipment Station</> to craft weapons and utilities that you can equip onto your Drone.\r\n\r\nFirst use the equipment station to <Bold>research</> available equipment by inserting <Bold>Tech Points</>, then once researched you can <Bold>craft</> the equipment by inserting required materials and parts.\r\n\r\nOnce crafted, the equipment can be equipped onto your Drone using the <Bold>Drone</> button at the top of the screen.":
        "<Bold>장비 정거장</>을 사용해 드론에 장착할 무기와 유틸리티를 제작하세요.\r\n\r\n먼저 <Bold>기술 포인트</>를 삽입해 사용 가능한 장비를 <Bold>연구</>한 다음, 연구 완료 후 필요한 재료와 부품을 삽입해 장비를 <Bold>제작</>합니다.\r\n\r\n제작된 장비는 화면 상단의 <Bold>드론</> 버튼을 사용해 드론에 장착할 수 있습니다.",
    "<Bold>Wormholes</> can be used to connect stations in different locations together and automatically transport items and gases between them.\r\n\r\nConnect a wormhole to another by selecting it in the list of available wormholes. Once connected, items and gases can flow between the two stations using <Bold>links</>, <Bold>tug links</> and <Bold>pipe connections</>.\r\n\r\nWormholes consume <Bold>Exotic Matter</> while in use, so make sure you have a steady supply.\r\n\r\nWormholes can also be used to <Bold>extend the range</> of your station's defences, drone reach and other functions across multiple zones.":
        "<Bold>웜홀</>은 서로 다른 위치의 스테이션을 연결하고 그 사이에서 아이템과 가스를 자동으로 운송하는 데 사용할 수 있습니다.\r\n\r\n사용 가능한 웜홀 목록에서 선택하여 다른 웜홀에 연결합니다. 연결되면 <Bold>연결</>, <Bold>예인선 연결</>, <Bold>파이프 연결</>을 사용해 두 스테이션 간에 아이템과 가스가 흐를 수 있습니다.\r\n\r\n웜홀은 사용 중에 <Bold>엑조틱 매터</>를 소비하므로 안정적인 공급을 확보하세요.\r\n\r\n웜홀은 여러 구역에 걸쳐 스테이션 방어, 드론 도달 거리, 기타 기능의 <Bold>범위를 확장</>하는 데에도 사용할 수 있습니다.",
}
